/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kakurosolver;

import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {
        printAllCombinations();
    }

    private static void printAllCombinations() {
        final var resolver = new CombinationResolverImpl();

        for (int i = 2; i <= 9; i++) {
            System.out.println(i);
            for (int y = 3; y <= 49; y++) {
                final var solution = resolver.getCombinations(y, i);
                final var solutions = solution.stream()
                        .map(combo -> combo.stream()
                                .map(String::valueOf)
                                .collect(Collectors.joining()))
                        .collect(Collectors.joining(" "));
                if (!solutions.isEmpty()) {
                    System.out.println(y + ": " + solutions);
                }
            }
        }
    }
}
