/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kakurosolver;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

import java.util.stream.Collectors;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    private static void printAllCombinations() {
        final var resolver = new CombinationResolverImpl();

        for (int i = 2; i <= 9; i++) {
            System.out.println(i);
            for (int y = 3; y <= 49; y++) {
                final var solution = resolver.getCombinations(y, i);
                final var solutions = solution.stream()
                        .map(combo -> combo.stream()
                                .map(String::valueOf)
                                .collect(Collectors.joining()))
                        .collect(Collectors.joining(" "));
                if (!solutions.isEmpty()) {
                    System.out.println(y + ": " + solutions);
                }
            }
        }
    }

    @Override
    public void start(final Stage primaryStage) throws Exception {
        primaryStage.setTitle("Hello World!");
        Button btn = new Button();
        btn.setText("Say 'Hello World'");
        btn.setOnAction(new EventHandler<ActionEvent>() {

            @Override
            public void handle(ActionEvent event) {
                System.out.println("Hello World!");
            }
        });

        StackPane root = new StackPane();
        root.getChildren().add(btn);
        primaryStage.setScene(new Scene(root, 300, 250));
        primaryStage.show();
    }
}
